FROM althack/ros2:humble-dev

ENV DEBIAN_FRONTEND=noninteractive

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | gpg --dearmor --batch --yes -o /usr/share/keyrings/ros-archive-keyring.gpg

# Add the ROS 2 repository for Jazzy (Ubuntu 24.04 is "noble")
RUN echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu noble main" > /etc/apt/sources.list.d/ros2.list

RUN apt update

RUN apt install -y git tini

RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] https://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
apt-get update && \
apt-get install gz-harmonic -y

RUN apt install -y ros-humble-ros-gzharmonic

RUN mkdir /app

WORKDIR /app

RUN git clone -b v2.4.3 https://github.com/eProsima/Micro-XRCE-DDS-Agent.git

WORKDIR /app/Micro-XRCE-DDS-Agent

RUN mkdir build

WORKDIR /app/Micro-XRCE-DDS-Agent/build

RUN cmake ..

RUN make

RUN make install

RUN ldconfig /usr/local/lib

WORKDIR /app

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc

RUN echo 'export PATH="$PATH:/cmd"' >> /root/.bashrc

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD [ "/entrypoint.sh" ]